[config]
# will be set to mainnet by default if omitted
rpc = "https://fullnode.devnet.sui.io:443"

[packages]
# Kraken = { git = "https://github.com/gmove-io/kraken.git", subdir = "package", rev = "main" }
Kraken = { local = "../../kraken/package/" }
