[config]
# will be set to mainnet by default if omitted
# rpc = "https://fullnode.testnet.sui.io:443"
# rpc = "https://sui-testnet-endpoint.blockvision.org:443"
rpc = "https://rpc-testnet.suiscan.xyz:443"
# rpc = "https://sui-testnet.nodeinfra.com:443"

[packages]
# AccountExtensions = { git = "https://github.com/account-tech/move-framework.git", subdir = "packages/extensions", rev = "testnet" }
# AccountProtocol = { git = "https://github.com/account-tech/move-framework.git", subdir = "packages/protocol", rev = "testnet" }
# AccountActions = { git = "https://github.com/account-tech/move-framework.git", subdir = "packages/actions", rev = "testnet" }
AccountExtensions = { local = "../../../move-framework/packages/extensions" }
AccountProtocol = { local = "../../../move-framework/packages/protocol" }
AccountActions = { local = "../../../move-framework/packages/actions" }
